# Configuration for CircleCI
version: 2.1
orbs:
  matlab: mathworks/matlab@0.3.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: "Switch to Python 3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - matlab/install
      - matlab/run-command:
          command: addpath dev-kit; disp('Hello, world!')
      
